### ISSUE TITLE
Add support for constructor with default parameter

### ISSUE THREAD

**Issue by vpmedia** [Kegsay/flow-jsdoc#14]
Constructor with default parameter does not gets converted:

      /**
       * TEXT
       * @param {string} key - TEXT
       * @property {string} key - TEXT
       * @constructor
       */
      constructor(key = 'VALUE') {
        this.key = key;
      }

If I remove the default value "= 'VALUE'") it's okay..

**Comment by vpmedia** [comment]
Also I'm noticing the same issue using method parameter default values:

Source:

    /* @flow */
    class Foo {
      /**
       * Construct a Foo.
       * @constructor
       * @param {string} bar The bar
       */
      constructor(bar = 'baz') {
        this.bar = bar;
      }
    
      /**
       * Do baz
       * @param {string=} key Optional key
       * @return {?Object}
       */
      baz(key = 'foo') : ?Object {
        return null;
      }
    }

Converted:

    /* @flow */
    class Foo {
      /**
       * Construct a Foo.
       * @constructor
       * @param {string} bar The bar
       */
      constructor(bar = 'baz') {
        this.bar = bar;
      }
    
      /**
       * Do baz
       * @param {string=} key Optional key
       * @return {?Object}
       */
      baz(key = 'foo') {
        return null;
      }
    }

**Comment by vpmedia** [comment]
I've tried the different syntaxes described here but no luck:
http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values

Pkg versions:

    "flow-bin": "^0.36.0",
    "flow-jsdoc": "^0.2.2",
    "flow-typed": "^2.0.0",

**Comment by Kegsay** [comment]
Default parameters should work on `master`, it just hasn't been released yet. If you can confirm that this works for you on `master` that'd be great.

**Comment by vpmedia** [comment]
Yes, I can confirm it's working with the git version. Thanks!
