### ISSUE TITLE
Integration with Webpack/Babel

### ISSUE THREAD

**Issue by LeonardoGentile** [Kegsay/flow-jsdoc#19]
Hello,
thanks very much for your efforts!
I'm wondering how to integrate this into a webpack/babel project?

When in developing mode for a webpack project I'm not particularly interested into getting the compiled js (with flow types) but: 
ES6+JsDoc with Flow Type Annotation -> ES5 + Flow (standard annotations) -> ES5 (without flow)

Any idea how to integrate this?

**Comment by Kegsay** [comment]
Starting with ES6 + JSDoc:
 - Run it through `flow-jsdoc`: you'll end up with ES6 + Flow
 - Run it through babel to transform ES6 -> ES5.
 - Strip flow-type annotations (there's a babel plugin for that - https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-flow-strip-types )
