### ISSUE TITLE
Handling JSDoc comments generation from flow syntax

### ISSUE THREAD

**Issue by Heliodromel** [Kegsay/flow-jsdoc#24]
Hi !

Currently the project is generating flow syntas from jsdoc but do you think it would be able to go the other way around ?

From the following code :

    function foo(bar: Array<Foobar>, baz: Function) : number {
        return 42;
    }

Generate the JSDoc comment :+1: 

    /**
     * @param {Foobar[]} bar
     * @param {Function} baz
     * @return {number}
     */
    function foo(bar: Array<Foobar>, baz: Function) : number {
        return 42;
    }

Regards,

**Comment by Kegsay** [comment]
This isn't a goal of this project currently.

**Comment by Heliodromel** [comment]
Ok, thanks for your answer !
