### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by dignifiedquire** [Kegsay/flow-jsdoc#3]
Hey, first thanks for making this, this looks really cool. When trying this out I was realising that optional parameters don't seem to work. For example

``` js
// Input

/*
 * @param {string} [optional=world] 
 * @return {string}
 */
myClassFunction (greeter) {
  if (greeter) return 'hello ' + greeter
  return 'hello world'
}
```

will not be transformed at all.

**Comment by Kegsay** [comment]
Currently only Closure Compiler style optional parameters are supported, e.g:
```javascript
/*
 * @param {string=} greeter
 * @return {string}
 */
myClassFunction (greeter) {
  if (greeter) return 'hello ' + greeter
  return 'hello world'
}
```

Which are translated to nullable types.

**Comment by Kegsay** [comment]
It looks like Doctrine isn't parsing optional params in `[form]`. Will need to go hunting for a fix.

**Comment by Kegsay** [comment]
Looks like I needed to pass the poorly-named `sloppy` param to Doctrine to get it to parse that syntax. Done now though: fixed [with tests](https://github.com/Kegsay/flow-jsdoc/blob/master/tests/input/11-optional-params.js).
