### ISSUE TITLE
Doesn't seem to support ES6 fat arrow functions

### ISSUE THREAD

**Issue by erahhal** [Kegsay/flow-jsdoc#5]
for instance:

```
const obj = {
    /**
     * @function
     * @param {string} a
     * @param {string} b
     * @return {number}
     */
    func: (a, b) => {
        return 1;
    },
};
```

or

```
functionWithCallback(
/**
 * @function
 * @param {string} a
 * @param {string} b
 * @return {number}
 */
(a, b) => {
    return 1;
}
);
```

**Comment by Kegsay** [comment]
Thanks for reporting! Will look into it and add tests for these scenarios when I fix them.

**Comment by Kegsay** [comment]
It's not the fact that they are anonymous functions. It's because you're using ES6 fat arrows which the project doesn't handle yet.

**Comment by Kegsay** [comment]
Fixed! Your examples now form [part of the test suite](https://github.com/Kegsay/flow-jsdoc/blob/master/tests/input/10-es6-fat-arrows.js). Thanks!

**Comment by erahhal** [comment]
Great, thanks for this!
