### ISSUE TITLE
npm package has DOS line endings

### ISSUE THREAD

**Issue by aspyrx** [Kegsay/flow-jsdoc#6]
As the issue title states, the published package has DOS line endings (`\r\n` instead of `\n`), which causes attempts to run on Unix-like systems to fail with the following error:
```
/usr/bin/env: ‘node\r’: No such file or directory
```

Tools like dos2unix may be of use here.

**Comment by Kegsay** [comment]
Oh, boo. That makes sense. I was relying on git being sensible but of course NPM isn't sensible. Really it should always be `\n`, I just occasionally use Windows when working on this project. Will fix, thanks.

**Comment by Kegsay** [comment]
Re-released as 0.2.2 with LFs. I can confirm this now works on OSX when installed using `npm install -g flow-jsdoc`. Thanks for reporting it!

**Comment by aspyrx** [comment]
Thanks for the quick turnaround and cool package!
