### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by wardpeet** [Kegsay/flow-jsdoc#8]
A few dependencies are out of date. (npm outdated)

![image](https://cloud.githubusercontent.com/assets/1120926/21508152/da176c0a-cc7e-11e6-901c-8aeb7260255a.png)

**Comment by Kegsay** [comment]
Sorry, but I have zero desire to "keep up the Joneses" on dependencies. I do not trust the JS ecosystem enough. It's bad enough I'm not pinning on versions and instead using `^` to catch minor updates. I have no desire to keep up-to-date **for no good reason**.

If there are security updates, noticeable performance-impacting improvements, or features which this project would benefit from, then I would absolutely update ASAP, but to say "you should probably use the latest dependencies for no particular reason" is not acceptable for me.

If there is a particular *reason* why I should update either `doctrine`, `glob` or `nopt` then please open respective issues for this and I shall be sure to update in a very timely manner. My apologies if this seems blunt, and I don't intend to appear ungrateful for you to point this out, but I hope you can understand my position here.
