### ISSUE TITLE
Add more comments to functions

### ISSUE THREAD

**Issue by wardpeet** [Kegsay/flow-jsdoc#9]
Would you mind splitting up the index.js in some smaller files and make the code a bit more manageable?

* Like introducing "constants" instead of strings.
* Splitting files

**Comment by Kegsay** [comment]
> Like introducing "constants" instead of strings.

Not going to happen. You gain absolutely nothing from introducing constants in JS. It's not like a compiled language where your compiler will whine at you if you mis-spell `MY_CONSTANT` as `MY_CONTSANT`. You'll just get `undefined` errors instead, and are introducing another layer of indirection which makes code more convoluted (you cannot tell at a glance if this is a `Number` or a `String` or whatever, you need to find where the constant is declared first). If there is a linter which will warn/error on usage of unqualified (without `window`) global variable usage then I would reconsider this policy.

> Splitting files

I assume this is aimed at `index.js` as `app.js` is the CLI. Assuming this is the case, `index.js` is currently sitting at 381 lines with comments and whitespace. This, in my opinion, is not excessive. There are commented functions which break up the code. If you feel this can be made clearer, please explain exactly where and how this, in your opinion, makes the code clearer. I'm always looking to improve code readability, so I'm open to suggestions on structure. That being said, I'm **not** open to creating many files/functions for no good reason (good reasons being code re-use or logical structuring). Having too many files/functions obfuscates code as it makes it hard to work out exactly what this code is doing as you need to consult many files and follow the chain of function calls to work out what actual code is being run.

---

I feel your heart is in the right place, so I would value some feedback here. Please give some examples which you feel would make the code clearer and explain yourself a bit more, and I will gladly make the changes you suggest if I agree with them.

Leaving this open pending feedback.

**Comment by wardpeet** [comment]
Thanks for the big comment. Sorry for updating so late.

I do feel your points of not splitting which I think are valid.
The reason why I like code splitting more is that you can write a lot of comments at the top of your file without making your file too long or unreadable because you only have the relevant functions inside for those operations.

Another approach is updating documentation on all functions I might try this in a few PR's but probably better for the owner to update .

Talking for example about:
```function decorateClasses(node) {```

**Comment by Kegsay** [comment]
More documentation on functions declarations would be most welcome: renaming this issue to track that.

**Comment by SebastienDaniel** [comment]
@Kegsay 
JS isn't a compiled language, you're right, but V8 does JIT compilation and constants allows for compilation-time optimisations. Sure it wont be a game-changer in terms of speed for this code base, but it's important to point out.
Also, constants provide contextual names to *magic values*, which eases maintenance.

**Comment by Kegsay** [comment]
> V8 does JIT compilation and constants allows for compilation-time optimisations

Said optimisations can be equally applied when referencing `"constant strings"`, which if anything is *easier* because you don't need to check for modifications elsewhere in the code. I would love to be shown otherwise though!

> constants provide contextual names to magic values

This is absolutely true and is one of the few reasons why I would actually bother to do this. However, this almost always applies to Numbers and Booleans rather than Strings which will often have the exact same name as the constant it is defining. This particular issue was recommending making strings become constants, which just adds needless indirections.

**Comment by Kegsay** [comment]
Added some more comments in https://github.com/Kegsay/flow-jsdoc/commit/084491e983bdee0bd9f255fc1283643c9f42176a
